### ISSUE TITLE
Nothing writes to log file

### ISSUE THREAD

**Issue by robross0606** [SerayaEryn/fast-file-rotate#22]
The log file is created with the correct name, but literally nothing ever goes into it.  It remains an empty file.  I can swap this out with standard Winston.transports.File and everything goes into it just fine.

**Comment by SerayaEryn** [comment]
`fast-fast-rotate` buffers 4096 Bytes before it starts to write to the file.
I guess that is the reason why your file is empty.

**Comment by SerayaEryn** [comment]
I am cloding this now. Feel free to reopen the issue if needed.
